# Generated by Django 2.2.6 on 2021-05-23 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50, verbose_name='Название товара')),
                ('name', models.CharField(max_length=30, verbose_name='Ваше имя')),
                ('phone', models.IntegerField(max_length=25, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ваш комментарий')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название товара')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Фото')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductCategory')),
            ],
        ),
    ]
